name: Python CI
on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
      - 'samples/**'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
      - 'samples/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    concurrency:
      group: python-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -e ./python
      - run: ruff format --check python
      - run: ruff check python
      - run: pytest -q
